name: ZetaCore
version: 1.1.3
author: YeetManLord
main: com.github.yeetmanlord.zeta_core.ZetaCore
description: All Zeta series plugins rely on this for functioning and code consistency. This also acts as a management plugin to enable, disable, and change the settings of various Zeta plugins.
api-version: 1.13

permissions:
    zeta.admin:
        description: Allows access to all ZetaCore commands
        default: op

commands:
  zeta_settings:
    description: Opens the local settings gui
    usage: /<command>
    permission: zeta.admin
    aliases: [zeta, zeta_local_settings]
  test:
    description: Test command. Runs test cases on reflection api
    usage: /<command>
    permission: zeta.admin